<?php

/**
 * Undocumented function
 *
 * @author Raja <raja@email.com>
 *
 * @param integer $a
 * @param integer $b
 * @return void
 */
function addTwoNum(int $a, int $b)
{
	return $a + $b;
}

echo 'If you see 4, then the function addTwoNum is running: ' . addTwoNum(2, 2);
echo '<br><br>';
?>

<a href="\Documentation\html\1___block___commenting_8php.html">HTML Documentation generated by Doxygen Windows 10 application for this PHP file is here.</a><br>
